# Generated by Django 3.1.2 on 2020-10-31 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201031_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
